// <auto-generated />
namespace Rentflix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageAddedMovie2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageAddedMovie2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812290921463_ImageAddedMovie2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
